# wrangler.toml

# 您的 Worker 名稱
name = "pokemon"

# 主程式入口點 (TypeScript)
main = "src/worker.ts"

# 相容性日期
compatibility_date = "2025-08-05"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "POKEMON_KV"
id = "a6aecf7af8304faabc3d8620b7e66bdd"
